python src/scripts/partition.py --in_file data/fever/train.ns.pages.p1.jsonl --out_file data/ablation/10 --split 1
python src/scripts/partition.py --in_file data/fever/train.ns.pages.p1.jsonl --out_file data/ablation/9 --split 0.9
python src/scripts/partition.py --in_file data/fever/train.ns.pages.p1.jsonl --out_file data/ablation/8 --split 0.8
python src/scripts/partition.py --in_file data/fever/train.ns.pages.p1.jsonl --out_file data/ablation/7 --split 0.7
python src/scripts/partition.py --in_file data/fever/train.ns.pages.p1.jsonl --out_file data/ablation/6 --split 0.6
python src/scripts/partition.py --in_file data/fever/train.ns.pages.p1.jsonl --out_file data/ablation/5 --split 0.5
python src/scripts/partition.py --in_file data/fever/train.ns.pages.p1.jsonl --out_file data/ablation/4 --split 0.4
python src/scripts/partition.py --in_file data/fever/train.ns.pages.p1.jsonl --out_file data/ablation/3 --split 0.3
python src/scripts/partition.py --in_file data/fever/train.ns.pages.p1.jsonl --out_file data/ablation/2 --split 0.2
python src/scripts/partition.py --in_file data/fever/train.ns.pages.p1.jsonl --out_file data/ablation/1 --split 0.1
python src/scripts/partition.py --in_file data/fever/train.ns.pages.p1.jsonl --out_file data/ablation/09 --split 0.09
python src/scripts/partition.py --in_file data/fever/train.ns.pages.p1.jsonl --out_file data/ablation/08 --split 0.08
python src/scripts/partition.py --in_file data/fever/train.ns.pages.p1.jsonl --out_file data/ablation/07 --split 0.07
python src/scripts/partition.py --in_file data/fever/train.ns.pages.p1.jsonl --out_file data/ablation/06 --split 0.06
python src/scripts/partition.py --in_file data/fever/train.ns.pages.p1.jsonl --out_file data/ablation/05 --split 0.05
python src/scripts/partition.py --in_file data/fever/train.ns.pages.p1.jsonl --out_file data/ablation/04 --split 0.04
python src/scripts/partition.py --in_file data/fever/train.ns.pages.p1.jsonl --out_file data/ablation/03 --split 0.03
python src/scripts/partition.py --in_file data/fever/train.ns.pages.p1.jsonl --out_file data/ablation/02 --split 0.02
python src/scripts/partition.py --in_file data/fever/train.ns.pages.p1.jsonl --out_file data/ablation/01 --split 0.01
python src/scripts/partition.py --in_file data/fever/train.ns.pages.p1.jsonl --out_file data/ablation/009 --split 0.009
python src/scripts/partition.py --in_file data/fever/train.ns.pages.p1.jsonl --out_file data/ablation/008 --split 0.008
python src/scripts/partition.py --in_file data/fever/train.ns.pages.p1.jsonl --out_file data/ablation/007 --split 0.007
python src/scripts/partition.py --in_file data/fever/train.ns.pages.p1.jsonl --out_file data/ablation/006 --split 0.006
python src/scripts/partition.py --in_file data/fever/train.ns.pages.p1.jsonl --out_file data/ablation/005 --split 0.005
python src/scripts/partition.py --in_file data/fever/train.ns.pages.p1.jsonl --out_file data/ablation/004 --split 0.004
python src/scripts/partition.py --in_file data/fever/train.ns.pages.p1.jsonl --out_file data/ablation/003 --split 0.003
python src/scripts/partition.py --in_file data/fever/train.ns.pages.p1.jsonl --out_file data/ablation/002 --split 0.002
python src/scripts/partition.py --in_file data/fever/train.ns.pages.p1.jsonl --out_file data/ablation/001 --split 0.001
python src/scripts/partition.py --in_file data/fever/train.ns.pages.p1.jsonl --out_file data/ablation/0009 --split 0.0009
python src/scripts/partition.py --in_file data/fever/train.ns.pages.p1.jsonl --out_file data/ablation/0008 --split 0.0008
python src/scripts/partition.py --in_file data/fever/train.ns.pages.p1.jsonl --out_file data/ablation/0007 --split 0.0007
python src/scripts/partition.py --in_file data/fever/train.ns.pages.p1.jsonl --out_file data/ablation/0006 --split 0.0006
python src/scripts/partition.py --in_file data/fever/train.ns.pages.p1.jsonl --out_file data/ablation/0005 --split 0.0005
python src/scripts/partition.py --in_file data/fever/train.ns.pages.p1.jsonl --out_file data/ablation/0004 --split 0.0004
python src/scripts/partition.py --in_file data/fever/train.ns.pages.p1.jsonl --out_file data/ablation/0003 --split 0.0003
python src/scripts/partition.py --in_file data/fever/train.ns.pages.p1.jsonl --out_file data/ablation/0002 --split 0.0002
python src/scripts/partition.py --in_file data/fever/train.ns.pages.p1.jsonl --out_file data/ablation/0001 --split 0.0001


